"""initial schema

Revision ID: b60554abe5bb
Revises:
Create Date: 2026-09-16 02:29:17.717114+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b60554abe5bb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buy_boxes",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("industries", postgresql.ARRAY(sa.String(length=120)), nullable=False),
        sa.Column("countries", postgresql.ARRAY(sa.String(length=2)), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("region", sa.String(length=120), nullable=True),
        sa.Column("radius_km", sa.Integer(), nullable=False),
        sa.Column("revenue_min", sa.Integer(), nullable=True),
        sa.Column("revenue_max", sa.Integer(), nullable=True),
        sa.Column("employees_min", sa.Integer(), nullable=True),
        sa.Column("employees_max", sa.Integer(), nullable=True),
        sa.Column("exclude_pe_owned", sa.Boolean(), nullable=False),
        sa.Column("weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "companies",
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=True),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("street", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("region", sa.String(length=120), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column(
            "geo",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("industry_label", sa.String(length=160), nullable=True),
        sa.Column("industry_code", sa.String(length=16), nullable=True),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column("employee_band", sa.String(length=16), nullable=True),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.Column("revenue_low", sa.Integer(), nullable=True),
        sa.Column("revenue_high", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain"),
    )
    op.create_index(op.f("ix_companies_country"), "companies", ["country"], unique=False)
    op.create_index(
        "ix_companies_country_industry", "companies", ["country", "industry_code"], unique=False
    )
    op.create_index("ix_companies_geo", "companies", ["geo"], unique=False, postgresql_using="gist")
    op.create_index(
        op.f("ix_companies_industry_code"), "companies", ["industry_code"], unique=False
    )
    op.create_index(
        "ix_companies_name_trgm",
        "companies",
        ["normalized_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalized_name": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_companies_normalized_name"), "companies", ["normalized_name"], unique=False
    )
    op.create_index(op.f("ix_companies_phone_e164"), "companies", ["phone_e164"], unique=False)
    op.create_table(
        "company_sources",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "source", "external_id", name="uq_company_source"),
    )
    op.create_index(
        op.f("ix_company_sources_company_id"), "company_sources", ["company_id"], unique=False
    )
    op.create_table(
        "field_values",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "field", "source", name="uq_field_value_per_source"),
    )
    op.create_index(
        op.f("ix_field_values_company_id"), "field_values", ["company_id"], unique=False
    )
    op.create_index("ix_field_values_field", "field_values", ["field"], unique=False)
    op.create_table(
        "people",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("role", sa.String(length=120), nullable=True),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("appointed_year", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("email_status", sa.String(length=24), nullable=False),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_people_company_id"), "people", ["company_id"], unique=False)
    op.create_table(
        "scores",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("buy_box_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["buy_box_id"], ["buy_boxes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scores_buy_box_id"), "scores", ["buy_box_id"], unique=False)
    op.create_index("ix_scores_buy_box_rank", "scores", ["buy_box_id", "score"], unique=False)
    op.create_index(
        "ix_scores_company_buy_box", "scores", ["company_id", "buy_box_id"], unique=True
    )
    op.create_index(op.f("ix_scores_company_id"), "scores", ["company_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scores_company_id"), table_name="scores")
    op.drop_index("ix_scores_company_buy_box", table_name="scores")
    op.drop_index("ix_scores_buy_box_rank", table_name="scores")
    op.drop_index(op.f("ix_scores_buy_box_id"), table_name="scores")
    op.drop_table("scores")
    op.drop_index(op.f("ix_people_company_id"), table_name="people")
    op.drop_table("people")
    op.drop_index("ix_field_values_field", table_name="field_values")
    op.drop_index(op.f("ix_field_values_company_id"), table_name="field_values")
    op.drop_table("field_values")
    op.drop_index(op.f("ix_company_sources_company_id"), table_name="company_sources")
    op.drop_table("company_sources")
    op.drop_index(op.f("ix_companies_phone_e164"), table_name="companies")
    op.drop_index(op.f("ix_companies_normalized_name"), table_name="companies")
    op.drop_index(
        "ix_companies_name_trgm",
        table_name="companies",
        postgresql_using="gin",
        postgresql_ops={"normalized_name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_companies_industry_code"), table_name="companies")
    op.drop_index("ix_companies_geo", table_name="companies", postgresql_using="gist")
    op.drop_index("ix_companies_country_industry", table_name="companies")
    op.drop_index(op.f("ix_companies_country"), table_name="companies")
    op.drop_table("companies")
    op.drop_table("buy_boxes")
    # ### end Alembic commands ###
