"""do not contact list

Revision ID: fa80cc4892fb
Revises: 1d7ac10cf98b
Create Date: 2026-09-17 18:06:29.276029+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fa80cc4892fb"
down_revision: str | None = "1d7ac10cf98b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppression_entries",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=320), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "value", name="uq_suppression_entry"),
    )
    op.create_index(
        op.f("ix_suppression_entries_kind"), "suppression_entries", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_suppression_entries_value"), "suppression_entries", ["value"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_suppression_entries_value"), table_name="suppression_entries")
    op.drop_index(op.f("ix_suppression_entries_kind"), table_name="suppression_entries")
    op.drop_table("suppression_entries")
    # ### end Alembic commands ###
