"""buy box mode

Revision ID: 3af064cbd8ea
Revises: 8f245cbe9ac8
Create Date: 2026-09-17 03:40:23.216348+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3af064cbd8ea"
down_revision: str | None = "8f245cbe9ac8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Every Buy Box saved before modes existed was an acquisition search, so that is
    # what existing rows become. The default is dropped so new rows must choose.
    op.add_column(
        "buy_boxes",
        sa.Column("mode", sa.String(length=16), nullable=False, server_default="acquisition"),
    )
    op.alter_column("buy_boxes", "mode", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("buy_boxes", "mode")
    # ### end Alembic commands ###
