"""keep merge decisions

Revision ID: 8f245cbe9ac8
Revises: 3ad5da77cd02
Create Date: 2026-09-17 00:56:16.209342+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8f245cbe9ac8"
down_revision: str | None = "3ad5da77cd02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("duplicate_candidates", "company_b_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(
        op.f("duplicate_candidates_company_b_id_fkey"), "duplicate_candidates", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "duplicate_candidates", "companies", ["company_b_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "duplicate_candidates", type_="foreignkey")
    op.create_foreign_key(
        op.f("duplicate_candidates_company_b_id_fkey"),
        "duplicate_candidates",
        "companies",
        ["company_b_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("duplicate_candidates", "company_b_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
