"""corporate directors

Revision ID: bd9f75150b54
Revises: a65491100b69
Create Date: 2026-09-16 19:47:53.690434+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bd9f75150b54"
down_revision: str | None = "a65491100b69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows predate this column, so it arrives with a default; the default
    # is then dropped so new rows must state the answer explicitly.
    op.add_column(
        "people",
        sa.Column("is_company", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("people", "is_company", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("people", "is_company")
    # ### end Alembic commands ###
