"""industry keys

Revision ID: 1d7ac10cf98b
Revises: e500a86e5882
Create Date: 2026-09-17 17:29:33.973259+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1d7ac10cf98b"
down_revision: str | None = "e500a86e5882"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


LABEL_TO_KEY = {
    "HVAC": "hvac",
    "Plumbing": "plumbing",
    "Electrical contracting": "electrical",
    "Landscaping": "landscaping",
    "Accounting": "accounting",
    "Dental practice": "dental",
    "Veterinary practice": "veterinary",
    "Commercial cleaning": "commercial_cleaning",
}

CATEGORY_TO_KEY = {
    "hvac_services": "hvac",
    "air_duct_cleaning_service": "hvac",
    "plumbing": "plumbing",
    "electrician": "electrical",
    "landscaping": "landscaping",
    "landscape_architect": "landscaping",
    "accountant": "accounting",
    "general_dentistry": "dental",
    "cosmetic_dentist": "dental",
    "pediatric_dentist": "dental",
    "veterinarian": "veterinary",
    "office_cleaning": "commercial_cleaning",
    "cleaning_services": "commercial_cleaning",
    "b2b_cleaning_and_waste_management": "commercial_cleaning",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "industry_keys",
            postgresql.ARRAY(sa.String(length=40)),
            server_default="{}",
            nullable=False,
        ),
    )
    op.create_index(
        "ix_companies_industry_keys",
        "companies",
        ["industry_keys"],
        unique=False,
        postgresql_using="gin",
    )

    # Backfill from what was actually recorded, as a snapshot: migrations must not
    # import application code that may change later.
    for label, key in LABEL_TO_KEY.items():
        op.execute(
            sa.text(
                "update companies set industry_keys = array_append(industry_keys, :key) "
                "where industry_label = :label and not (:key = any(industry_keys))"
            ).bindparams(label=label, key=key)
        )
    for category, key in CATEGORY_TO_KEY.items():
        op.execute(
            sa.text(
                "update companies c set industry_keys = array_append(c.industry_keys, :key) "
                "where not (:key = any(c.industry_keys)) and exists ("
                "  select 1 from field_values f"
                "  where f.company_id = c.id and f.field = 'category' and f.value #>> '{}' = :category"
                ")"
            ).bindparams(category=category, key=key)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_companies_industry_keys", table_name="companies", postgresql_using="gin")
    op.drop_column("companies", "industry_keys")
    # ### end Alembic commands ###
