"""duplicate review queue

Revision ID: 3ad5da77cd02
Revises: bd9f75150b54
Create Date: 2026-09-17 00:49:16.909318+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3ad5da77cd02"
down_revision: str | None = "bd9f75150b54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "duplicate_candidates",
        sa.Column("company_a_id", sa.UUID(), nullable=False),
        sa.Column("company_b_id", sa.UUID(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_a_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["company_b_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_a_id", "company_b_id", name="uq_duplicate_pair"),
    )
    op.create_index(
        op.f("ix_duplicate_candidates_company_a_id"),
        "duplicate_candidates",
        ["company_a_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_candidates_company_b_id"),
        "duplicate_candidates",
        ["company_b_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_candidates_status"), "duplicate_candidates", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_duplicate_candidates_status"), table_name="duplicate_candidates")
    op.drop_index(op.f("ix_duplicate_candidates_company_b_id"), table_name="duplicate_candidates")
    op.drop_index(op.f("ix_duplicate_candidates_company_a_id"), table_name="duplicate_candidates")
    op.drop_table("duplicate_candidates")
    # ### end Alembic commands ###
