"""score may be unknown

Revision ID: a65491100b69
Revises: b60554abe5bb
Create Date: 2026-09-16 18:39:22.938376+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a65491100b69"
down_revision: str | None = "b60554abe5bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scores", "score", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scores", "score", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    # ### end Alembic commands ###
